In [11]:
import numpy as np

In [2]:
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
matrix = np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
matrix = np.random.randint(11, size=(5,5))
print(matrix)

[[ 0  0  6  0  4]
 [ 6  2  7  0  1]
 [ 2  2  8  2 10]
 [10  6  1  6  0]
 [ 5  8  4  3  0]]


In [7]:
matrix = np.random.rand(4,4)
print(matrix)

[[0.1095981  0.18949515 0.34545113 0.02454984]
 [0.76884843 0.94426749 0.07798229 0.15563862]
 [0.01938452 0.91811413 0.1355845  0.71111297]
 [0.83757705 0.65751312 0.98031138 0.97302879]]


In [10]:
M1 = np.random.randint(1, 11, 5)
M2 = np.random.randint(1, 11, 5)
print(M1, M2)
print(M1 + M2)
print(M1 - M2)
print(M1 * M2)

[5 8 3 7 8] [ 7 10  4 10  5]
[12 18  7 17 13]
[-2 -2 -1 -3  3]
[35 80 12 70 40]


In [12]:
V1 = np.random.rand(7)
V2 = np.random.rand(7)
print(np.dot(V1,V2))

1.7834200456264746


In [16]:
matrix1 = np.random.randint(1, 11,(2, 2))
matrix2 = np.random.randint(1, 11,(2, 3))
print(np.dot(matrix1, matrix2))

[[58 22 48]
 [73 22 57]]


In [17]:
matrix = np.random.randint(1, 11, (3, 3))
a_inv = np.linalg.inv(matrix)
print(a_inv)

[[ 0.00917431 -0.06422018  0.20183486]
 [-0.32110092  0.24770642 -0.06422018]
 [ 0.44954128 -0.14678899 -0.11009174]]


In [19]:
matrix = np.random.rand(4, 4)
print(matrix.T)

[[0.18264548 0.4007491  0.87713331 0.79608372]
 [0.04760793 0.60833717 0.64115307 0.0482504 ]
 [0.21327726 0.19776236 0.4316728  0.41790726]
 [0.56014889 0.19233851 0.54825805 0.24466676]]


In [20]:
matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.randint(1, 11, 4)
print(np.dot(matrix, vector))

[128 135 120]


In [21]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
print(np.dot(matrix, vector))

[1.02765656 1.16012927]


In [23]:
matrix1 = np.random.randint(1, 11,(2, 2))
matrix2 = np.random.randint(1, 11,(2, 2))
print(matrix1 * matrix2)

[[ 4 27]
 [45 15]]


In [24]:
matrix1 = np.random.randint(1, 11,(2, 2))
matrix2 = np.random.randint(1, 11,(2, 2))
print(matrix1 + matrix2)

[[ 9 13]
 [ 9 14]]


In [26]:
matrix = np.random.randint(1, 101,(5, 5))
print(np.sum(matrix))

1266


In [28]:
matrix1 = np.random.randint(1, 11,(4, 4))
matrix2 = np.random.randint(1, 11,(4, 4))
print(matrix1 - matrix2)

[[-6 -1  3  5]
 [ 3  0 -4 -6]
 [-2  3  7  1]
 [ 0  1 -3 -6]]


In [30]:
matrix = np.random.rand(3, 3)

vector_column = np.sum(matrix, axis=1)
print(vector_column.reshape(-1, 1))

[[1.65512646]
 [2.18474339]
 [1.31667284]]


In [31]:
matrix = np.random.randint(1, 11,(3, 4))
print(matrix**2)

[[ 64  16  64   9]
 [ 36   1 100  81]
 [  1   1  81   4]]


In [34]:
vector = np.random.randint(1, 51, 4)
print(np.sqrt(vector))

[4.89897949 6.32455532 3.16227766 5.74456265]
