In [ ]:
import numpy as np

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
indices = arr % 2 == 1
arr[indices] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
one_d = np.array([1, 2, 3, 4, 5, 6])
two_d = one_d.reshape(2, -1)
print(two_d)

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.random.randint(1, 11,(3, 4))
b = np.random.randint(1, 11,(2, 4))
print(np.vstack((a, b)))

[[ 2  2  6  2]
 [10  5  3  5]
 [ 8  8  3  1]
 [ 4  5 10  5]
 [ 4  4  9  7]]


In [ ]:
a = np.array([1, 2, 3])
exp_a = np.repeat(a, 3)
print(np.tile(exp_a, 2))

[1 1 1 2 2 2 3 3 3 1 1 1 2 2 2 3 3 3]


In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


In [ ]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
i = np.argsort(a)[::-1]
i_5 = i[:5]
print(a, i_5)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361] [15 10  3  7 18]


In [ ]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
nan_i = np.isnan(a)
a_cl = a[~nan_i]
print(a, a_cl)

[ 1.  2.  3. nan  5.  6.  7. nan] [1. 2. 3. 5. 6. 7.]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
diff = a -b
sq_diff = diff ** 2
sum_sq_diff = np.sum(sq_diff)
print(np.sqrt(sum_sq_diff))

6.708203932499369


In [ ]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
i = np.where(x == 1)[0]
print(i[4])

8


In [29]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
res = np.zeros_like(a, dtype=bool)

for i in range(1, len(a)):
  if a[i] == a[i-1]:
      res[i] = True
print(a, res)

[0 0 3 0 2 4 2 2 2 2] [False  True False False False False False  True  True  True]
